apiVersion: v1
kind: Service
metadata:
  name: kube-lbknocker
  labels:
    app.kubernetes.io/name: kube-lbknocker
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app.kubernetes.io/name: kube-lbknocker
