apiVersion: v1
kind: Service
metadata:
  name: service-example
  labels:
    app.kubernetes.io/name: service-example
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  loadBalancerSourceRanges:
  - 1.2.3.4/32
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: service-example
